### PR TITLE
Add a tab close button. Fixes #8

### LINKED ISSUE #8: Close tabs from the list
Close tabs by pressing an X-icon or middleclick on it.

### PR DESCRIPTION
**Pull request by mnoorenberghe**
Feel free to merge and make style adjustments to your own taste in a follow-up commit. That's normally easier than trying to explain them.

screen shot 2016-04-03 at 4 55 28 pm

### CODE REVIEW

**Comment by skyschub** [comment]
I'd make the icons the same color as the control icons for the groups. Also, I'd only show them on hover.

**Comment by skyschub** [comment]
> Feel free to merge and make style adjustments to your own taste

Oh, mh. I see. Will do it when I have some time. ;)

**Comment by mnoorenberghe** [comment]
> I'd make the icons the same color as the control icons for the groups.

I agree and I can do that.

> Also, I'd only show them on hover.

I considered this but it can be considered bad UX if a user clicks in the empty area to select the tab but then accidentally closes the tab. What do you think about that? I guess if I use `visibility:hidden` it will use a gutter that users shouldn't click in.

**Comment by skyschub** [comment]
They have to hover the element to click it, right? So I don't think "accidental closing" is an issue.

**Comment by mnoorenberghe** [comment]
The user may not have a chance to notice the close button appearing to stop their click.

**Comment by skyschub** [comment]
I've never got complains about accidental group closing, which has the same UI. I'd go with hiding the icons per default and think about that again if we get a complaint.

**Comment by mnoorenberghe** [comment]
Any preference for `display: none` vs. `visibility:hidden`? It will affect truncated tab titles. The latter is more performant and less likely to lead to accidental closing.

**Comment by skyschub** [comment]
`visibility`.

**Comment by mnoorenberghe** [comment]
OK, I'll make the two fixes now

**Comment by mnoorenberghe** [comment]
Fixed. Thanks for the quick reviews btw.!

**Comment by skyschub** [comment]
So actually, after a review, I am not fine with this PR right now. Take a look at the comparison screenshot (left: before, right: after)

screen-shot-2016-04-04-at-5 14 14-

You removed the `padding-top` and `padding-bottom` from `.tab-title`, probably to make positioning the close button easier. While I do understand that CSS is a bit tricky from time to time, this is something that needs to be resolved since the list looks really messy now.

For the sake of reusing some code, I suggest you to take a look at [data/components/group.js#L73-L90](https://github.com/denschub/firefox-tabgroups/blob/develop/src/data/components/group.js#L73-L90) where you can see I placed the title and the controls inside a `span.group-title`. The [`GroupControls` component](https://github.com/denschub/firefox-tabgroups/blob/develop/src/data/components/groupcontrols.js) renders a `span.group-controls`, which has child elements that [get displayed on hover](https://github.com/denschub/firefox-tabgroups/blob/develop/src/data/assets/css/groupspanel.css#L129-L132).

Although we only have one action for tabs at the moment, I can imagine further actions. Therefore, I suggest moving the actual close button into a `TabControls` component and use a similar layout as within the group. That way, you'll be able to reuse parts of the CSS from `.group-controls` and `.group-title`, including the little hacks that allow a proper positioning of the icons while maintaining the items padding.

**Comment by mnoorenberghe** [comment]
I can fix the padding but I was actually just cleaning it up to have proper vertical centering with vertical-align instead of previous approach of hard-coding pixel offsets. I didn't double-check if I maintained the exact height of the rows but I can make it match the old height.

I originally started having a container for the actions but then thought it's unlikely there will be others so removed it. I figured it could be added later when needed and in the meantime it can stay simpler.

**Comment by skyschub** [comment]
If you're still working on something, please add "WIP" or something to the title. I was actually about merging it if I didn't missed the padding.

I see no reason to not add a dedicated controls component to maintain the structure. But if you find a nice solution without adding more CSS hacks, fine.

**Comment by mnoorenberghe** [comment]
> If you're still working on something, please add "WIP" or something to the title. I was actually about merging it if I didn't missed the padding.

I wasn't still working on this. I think you have misunderstood.

> I see no reason to not add a dedicated controls component to maintain the structure. But if you find a nice solution without adding more CSS hacks, fine.

As far as I can tell, all I need to do is add padding to `.tab` to address your comment. No hacks required, it's actually cleaner with my patch as before I would need the magic numbers on each child.

**Comment by skyschub** [comment]
Oh, I thought you were working on this right now since you wrote "I was actually just cleaning it up" :)

> No hacks required, it's actually cleaner with my patch as before I would need the magic numbers on each child.

:+1:

**Comment by mnoorenberghe** [comment]
> Oh, I thought you were working on this right now since you wrote "I was actually just cleaning it up" :)

Oh, sorry, I meant that the reason I was touching the existing padding was to remove some magic numbers and use vertical-align.

**Comment by skyschub** [comment]
Right, communication issues are fun. But you'll still add some more spacing in this PR?

**Comment by mnoorenberghe** [comment]
yes

**Comment by skyschub** [comment]
@mnoorenberghe Ping?

**Comment by skyschub** [comment]
Closing this, will get obsolete with the new version.

**Pull request closed without merging**
